In [2]:
import pandas as pd
from sklearn.preprocessing import OneHotEncoder

# Sample data
data = {
    'w': [1.0, 2.0, 3.0, 4.0, 5.0, 6.0, 7.0, 8.0, 9.0, 10.0],
    'l': ['Al', '-', 'Zaman', ':', 'American', 'forces', 'killed', 'Shaikh', 'Abdullah', '...'],
    'x': ['Al', '-', 'Zaman', ':', 'american', 'force', 'kill', 'Shaikh', 'Abdullah', '...'],
    'p': ['PROPN', 'PUNCT', 'PROPN', 'PUNCT', 'ADJ', 'NOUN', 'VERB', 'PROPN', 'PROPN', '...'],
    'g': ['NNP', 'HYPH', 'NNP', ':', 'JJ', 'NNS', 'VBD', 'NNP', 'NNP', '...'],
    'f': [0, 1, 1, 1, 6, 7, 1, 7, 8, '...'],
    'e': ['root', 'punct', 'flat', 'punct', 'amod', 'nsubj', 'parataxis', 'obj', 'flat', '...'],
    'type': ['_', '_', '_', '_', '_', '_', '_', '_', '_', '...'],
    'gender': ['_', '_', '_', '_', '_', '_', '_', '_', '_', '...'],
    'Case': ['_', '_', '_', '_', '_', '_', '_', '_', '_', '...'],
    'Definite': ['_', '_', '_', '_', '_', '_', '_', '_', '_', '...'],
    'Degree': ['_', '_', '_', '_', 'Pos', '_', '_', '_', '_', '...'],
    'Foreign': ['_', '_', '_', '_', '_', '_', '_', '_', '_', '...'],
    'Gender': ['_', '_', '_', '_', '_', '_', '_', '_', '_', '...'],
    'Mood': ['_', '_', '_', '_', '_', '_', 'Ind', '_', '_', '...'],
    'Number': ['Sing', '_', 'Sing', '_', '_', 'Plur', '_', 'Sing', 'Sing', '...'],
    'Person': ['_', '_', '_', '_', '_', '_', '_', '_', '_', '...'],
    'Poss': ['_', '_', '_', '_', '_', '_', '_', '_', '_', '...'],
    'Reflex': ['_', '_', '_', '_', '_', '_', '_', '_', '_', '...'],
    'Tense': ['_', '_', '_', '_', '_', '_', 'Past', '_', '_', '...'],
    'Voice': ['_', '_', '_', '_', '_', '_', '_', '_', '_', '...'],
    'Type': ['_', '_', '_', '_', '_', '_', '_', '_', '_', '...']
}

# Create DataFrame
df = pd.DataFrame(data)

# One-hot encode categorical columns
categorical_columns = ['l', 'x', 'p', 'g', 'e', 'type', 'gender', 'Case', 'Definite', 'Degree', 'Foreign', 'Gender', 'Mood', 'Number', 'Person', 'Poss', 'Reflex', 'Tense', 'Voice', 'Type']
df_encoded = pd.get_dummies(df, columns=categorical_columns)

# Convert to vector
vectors = df_encoded.values

print(vectors)

[[1.0 0 False False False False True False False False False False False
  False False False True False False False False False False False False
  True False False False False False False True False False False False
  False False False False False True False True False True False True
  False True False False True False True False True False False True
  False False True False False True False True False True False False
  True False True False True]
 [2.0 1 True False False False False False False False False False True
  False False False False False False False False False False False False
  False True False False False True False False False False False False
  False False False False True False False True False True False True
  False True False False True False True False True False False True
  False False False True False True False True False True False False
  True False True False True]
 [3.0 1 False False False False False False False True False False False
  False False

In [6]:
import pandas as pd
from sklearn.preprocessing import OneHotEncoder, LabelEncoder

# Sample data
data = {'color': ['red', 'green', 'blue', 'green', 'red']}

# Create DataFrame
df = pd.DataFrame(data)

# One-Hot Encoding
one_hot_encoder = OneHotEncoder()
one_hot_encoded = one_hot_encoder.fit_transform(df[['color']])
one_hot_df = pd.DataFrame(one_hot_encoded.toarray(), columns=one_hot_encoder.get_feature_names_out(['color']))

# Label Encoding
label_encoder = LabelEncoder()
label_encoded = label_encoder.fit_transform(df['color'])
label_df = pd.DataFrame(label_encoded, columns=['color'])

print("One-Hot Encoded DataFrame:")
print(one_hot_df)
print("\nLabel Encoded DataFrame:")
print(label_df)

One-Hot Encoded DataFrame:
   color_blue  color_green  color_red
0         0.0          0.0        1.0
1         0.0          1.0        0.0
2         1.0          0.0        0.0
3         0.0          1.0        0.0
4         0.0          0.0        1.0

Label Encoded DataFrame:
   color
0      2
1      1
2      0
3      1
4      2


In [17]:
import pandas as pd
from sklearn.preprocessing import  LabelEncoder
data = {'color': ['red', 'green', 'blue', 'green', 'red']}
df = pd.DataFrame(data)
print(df)
label_encoder = LabelEncoder()
df['color'] = label_encoder.fit_transform(df['color'])
print(df)
print("-"*50)
mapping = dict(zip(label_encoder.classes_, label_encoder.transform(label_encoder.classes_).tolist()))
print(mapping)

   color
0    red
1  green
2   blue
3  green
4    red
   color
0      2
1      1
2      0
3      1
4      2
--------------------------------------------------
{'blue': 0, 'green': 1, 'red': 2}


In [10]:
file_path = "data/input/test.conllu"

In [9]:
import pandas as pd
from conll_df import conll_df
path = 'data/input/ro_rrt-ud-train.conllu'
df = conll_df(path, file_index=True)
df.head(40).to_csv('data/output/ro_rrt-ud-train.csv', index=False)

In [24]:
import pyconll

data = pyconll.load_from_file("data/input/test.conllu")
tokens =[]
for sentence in data:
    for token in sentence:
        token_info = {
            'id': token.id,
            'form': token.form,
            'lemma': token.lemma,
            'upos': token.upos,
            'xpos': token.xpos,
            'head': token.head,
            'deprel': token.deprel,
            'deps': token.deps,
            'misc': token.misc
        }
        for key, value in token.feats.items():
            token_info[key] = value
        tokens.append(token_info)

df = pd.DataFrame(tokens)
df.to_csv('data/output/test.csv', index=False)

In [33]:
import pandas as pd
import numpy as np


def remove_value_from_column(df, column_name, value):
    """
    Removes all occurrences of a value from a specified column in a DataFrame.

    Parameters:
    df (pd.DataFrame): The input DataFrame.
    column_name (str): The name of the column from which to remove the value.
    value: The value to be removed from the column.

    Returns:
    pd.DataFrame: The resulting DataFrame with the value removed from the specified column.
    """
    df[column_name] = df[column_name].replace(value, np.nan)
    return df

In [34]:
new_df = remove_value_from_column(df, 'deprel', 'punct')
new_df.to_csv('data/output/test_values_removed.csv', index=False)

In [4]:
from sklearn.feature_extraction.text import CountVectorizer
corpus = [
    'This',
    'This ',
    'And',
    'Is',
]
vectorizer = CountVectorizer()
X = vectorizer.fit_transform(corpus)
vectorizer.get_feature_names_out()
print(X.toarray())

[[0 0 1]
 [0 0 1]
 [1 0 0]
 [0 1 0]]
